        !COMPILER-GENERATED INTERFACE MODULE: Tue Oct  7 10:33:44 2025
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE VUMAT__genmod
          INTERFACE 
            SUBROUTINE VUMAT(NBLOCK,NDIR,NSHR,NSTATEV,NFIELDV,NPROPS,   &
     &LANNEAL,STEPTIME,TOTALTIME,DT,CMNAME,COORDMP,CHARLENGTH,PROPS,    &
     &DENSITY,STRAININC,RELSPININC,TEMPOLD,STRETCHOLD,DEFGRADOLD,       &
     &FIELDOLD,STRESSOLD,STATEOLD,ENERINTERNOLD,ENERINELASOLD,TEMPNEW,  &
     &STRETCHNEW,DEFGRADNEW,FIELDNEW,STRESSNEW,STATENEW,ENERINTERNNEW,  &
     &ENERINELASNEW)
              INTEGER(KIND=4) :: NPROPS
              INTEGER(KIND=4) :: NFIELDV
              INTEGER(KIND=4) :: NSTATEV
              INTEGER(KIND=4) :: NSHR
              INTEGER(KIND=4) :: NDIR
              INTEGER(KIND=4) :: NBLOCK
              INTEGER(KIND=4) :: LANNEAL
              REAL(KIND=8) :: STEPTIME
              REAL(KIND=8) :: TOTALTIME
              REAL(KIND=8) :: DT
              CHARACTER(LEN=8) :: CMNAME
              REAL(KIND=8) :: COORDMP(NBLOCK)
              REAL(KIND=8) :: CHARLENGTH(NBLOCK)
              REAL(KIND=8) :: PROPS(NPROPS)
              REAL(KIND=8) :: DENSITY(NBLOCK)
              REAL(KIND=8) :: STRAININC(NBLOCK,NDIR+NSHR)
              REAL(KIND=8) :: RELSPININC(NBLOCK,NSHR)
              REAL(KIND=8) :: TEMPOLD(NBLOCK)
              REAL(KIND=8) :: STRETCHOLD(NBLOCK,NDIR+NSHR)
              REAL(KIND=8) :: DEFGRADOLD(NBLOCK,NDIR+NSHR+NSHR)
              REAL(KIND=8) :: FIELDOLD(NBLOCK,NFIELDV)
              REAL(KIND=8) :: STRESSOLD(NBLOCK,NDIR+NSHR)
              REAL(KIND=8) :: STATEOLD(NBLOCK,NSTATEV)
              REAL(KIND=8) :: ENERINTERNOLD(NBLOCK)
              REAL(KIND=8) :: ENERINELASOLD(NBLOCK)
              REAL(KIND=8) :: TEMPNEW(NBLOCK)
              REAL(KIND=8) :: STRETCHNEW(NBLOCK,NDIR+NSHR)
              REAL(KIND=8) :: DEFGRADNEW(NBLOCK,NDIR+NSHR+NSHR)
              REAL(KIND=8) :: FIELDNEW(NBLOCK,NFIELDV)
              REAL(KIND=8) :: STRESSNEW(NBLOCK,NDIR+NSHR)
              REAL(KIND=8) :: STATENEW(NBLOCK,NSTATEV)
              REAL(KIND=8) :: ENERINTERNNEW(NBLOCK)
              REAL(KIND=8) :: ENERINELASNEW(NBLOCK)
            END SUBROUTINE VUMAT
          END INTERFACE 
        END MODULE VUMAT__genmod
